AppointmentSystem/AppointmentSystem/Controllers/BaseInfoController.cs
using AppointmentSystem.Models.DBModels;
using AppointmentSystem.Models.ViewModels.AppointmentModels;
using AppointmentSystem.Models.ViewModels.BaseInfoModels;
using AppointmentSystem.Models.ViewModels.SystemModels;
using AppointmentSystem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using System.Numerics;
using static AppointmentSystem.Models.ViewModels.SelectListModels;

namespace AppointmentSystem.Controllers
{
    public class BaseInfoController : Controller
    {
        private readonly BaseInfoService _baseinfoService;
        private readonly WebFunctions _functions;

        public BaseInfoController(EkasContext context)
        {
            _baseinfoService = new BaseInfoService(context);
            _functions = new WebFunctions(context);
        }

        #region -- 醫師基本資料 -- (Doctor)

        [Authorize]
        public IActionResult DoctorIndex()
        {
            //判斷cookie是員工還是顧客
            var user = HttpContext.User.Claims.ToList();

            if (user.FirstOrDefault(u => u.Type == "LoginType").Value == "EkUser")
            {
                List<DoctorIndexVM> doctors = _baseinfoService.GetDoctorListForIndex();
                ViewBag.Count = doctors.Count;

                return View(doctors);
            }
            else
            {
                return RedirectToAction("Login", "Appointment");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult DoctorCreate([FromForm] DoctorEditVM value)
        {
            var user = HttpContext.User.Claims.ToList();
            string DoctorId = _functions.GetGuid();

            while (_baseinfoService.CheckDoctorId(DoctorId))
                DoctorId = _functions.GetGuid();

            string FileId = "";

            if (value.DoctorImage.File != null)
                FileId = _functions.SaveFile(value.DoctorImage.File, user.FirstOrDefault(u => u.Type == "Account").Value);
            else
                FileId = _baseinfoService.GetDoctorImageIdByDoctorId(value.DoctorId);

            if (String.IsNullOrEmpty(value.DoctorNameEnglish))
                value.DoctorNameEnglish = "";
            if (String.IsNullOrEmpty(value.Memo))
                value.Memo = "";

            Doctor item = new Doctor()
            {
                Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                Modifier = user.FirstOrDefault(u => u.Type == "Account").Value,
                CreateDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                Status = "Y",

                Id = DoctorId,
                DoctorName = value.DoctorName,
                DoctorNameEnglish = value.DoctorNameEnglish,
                Introduction = value.Introduction,
                DepartmentTitle = value.DepartmentTitle,
                ColorHex = value.ColorHEX,
                Sort = _baseinfoService.GetDoctorCount() + 1,
                Memo = value.Memo,
                ImageFileId = FileId
            };
            _baseinfoService.CreateDoctor(item);

            //儲存醫師負責的療程
            //先刪除相關資料再新增
            string[] treatments = value.SelectedTreatment.Split(',');
            _baseinfoService.RemoveDoctorTreatment(value.DoctorId);

            foreach (var treatmentId in treatments)
            {
                Doctortreatment dt = new Doctortreatment()
                {
                    Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                    Modifier = user.FirstOrDefault(u => u.Type == "Account").Value,
                    CreateDate = DateTime.Now,
                    ModifyDate = DateTime.Now,
                    Status = "Y",

                    DoctorId = DoctorId,
                    TreatmentId = treatmentId
                };

                _baseinfoService.CreateDoctorTreatment(dt);
            }

            _functions.SaveSystemLog(new Systemlog
            {
                CreateDate = DateTime.Now,
                Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                UserAccount = user.FirstOrDefault(u => u.Type == "Account").Value,
                Description = "Add doctor id='" + DoctorId + "'."
            });

            return new JsonResult(DoctorId);
        }

        //[HttpGet]
        //[Authorize]
        //public IActionResult DoctorNameUpdate(string name, string id)
        //{
        //    string DoctorId = id;

        //    var user = HttpContext.User.Claims.ToList();

        //    Doctor item = new Doctor()
        //    {
        //        Modifier = user.FirstOrDefault(u => u.Type == "Account").Value,
        //        ModifyDate = DateTime.Now,

        //        DoctorName = name
        //    };

        //    _baseinfoService.UpdateDoctorName(id, user.FirstOrDefault(u => u.Type == "Account").Value, item);

        //    _functions.SaveSystemLog(new Systemlog
        //    {
        //        CreateDate = DateTime.Now,
        //        Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
        //        UserAccount = user.FirstOrDefault(u => u.Type == "Account").Value,
        //        Description = "Update doctor id='" + DoctorId + "'."
        //    });

        //    return new JsonResult(DoctorId);
        //}

        [HttpPost]
        [Authorize]
        public IActionResult DoctorUpdate([FromForm] DoctorEditVM value)
        {
            var user = HttpContext.User.Claims.ToList();
            string FileId = "";

            if (value.DoctorImage.File != null)
                FileId = _functions.SaveFile(value.DoctorImage.File, user.FirstOrDefault(u => u.Type == "Account").Value);
            else
                FileId = _baseinfoService.GetDoctorImageIdByDoctorId(value.DoctorId);

            if (String.IsNullOrEmpty(value.DoctorNameEnglish))
                value.DoctorNameEnglish = "";
            if (String.IsNullOrEmpty(value.Memo))
                value.Memo = "";

            Doctor item = new Doctor()
            {
                Modifier = user.FirstOrDefault(u => u.Type == "Account").Value,
                ModifyDate = DateTime.Now,

                DoctorName = value.DoctorName,
                DoctorNameEnglish = value.DoctorNameEnglish,
                Introduction = value.Introduction,
                DepartmentTitle = value.DepartmentTitle,
                ColorHex = value.ColorHEX,
                Memo = value.Memo,
                ImageFileId = FileId
            };
            _baseinfoService.UpdateDoctor(value.DoctorId, user.FirstOrDefault(u => u.Type == "Account").Value, item);

            //儲存醫師負責的療程
            //先刪除相關資料再新增
            string[] treatments = value.SelectedTreatment.Split(',');
            _baseinfoService.RemoveDoctorTreatment(value.DoctorId);

            foreach (var treatmentId in treatments)
            {
                Doctortreatment dt = new Doctortreatment()
                {
                    Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                    Modifier = user.FirstOrDefault(u => u.Type == "Account").Value,
                    CreateDate = DateTime.Now,
                    ModifyDate = DateTime.Now,
                    Status = "Y",

                    DoctorId = value.DoctorId,
                    TreatmentId = treatmentId
                };

                _baseinfoService.CreateDoctorTreatment(dt);
            }

            _functions.SaveSystemLog(new Systemlog
            {
                CreateDate = DateTime.Now,
                Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                UserAccount = user.FirstOrDefault(u => u.Type == "Account").Value,
                Description = "Update treatment id='" + value.DoctorId + "'."
            });

            return new JsonResult("OK");
        }

        [HttpGet]
        [Authorize]
        public IActionResult GetDoctorDetailData(string id)
        {
            DoctorEditVM doctor = _baseinfoService.GetDoctorById(id);
            List<TreatmentCheckboxList> TreatmentCheckboxList = _baseinfoService.GetDoctorTreatmentListForCheckbox(id);

            doctor.TreatmentList = TreatmentCheckboxList;

            return new JsonResult(doctor);
        }

        [HttpPost]
        [Authorize]
        public IActionResult saveDoctorSort(string[] items)
        {
            int i = 1;
            foreach (var item in items)
            {
                _baseinfoService.saveDoctorSort(item, i);
                i++;
            }

            return new JsonResult("OK");
        }



        #endregion

        #region -- 療程基本資料 -- (Treatment)

        [Authorize]
        public IActionResult TreatmentIndex()
        {
            //判斷cookie是員工還是顧客
            var user = HttpContext.User.Claims.ToList();

            if (user.FirstOrDefault(u => u.Type == "LoginType").Value == "EkUser")
            {
                List<TreatmentIndexVM> treatments = _baseinfoService.GetTreatmentListForIndex();
                ViewBag.Count = treatments.Count;

                return View(treatments);
            }
            else
            {
                return RedirectToAction("Login", "Appointment");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult TreatmentCreate([FromForm] TreatmentEditVM value)
        {
            var user = HttpContext.User.Claims.ToList();
            string TreatmentId = _functions.GetGuid();

            while (_baseinfoService.CheckTreatmentId(TreatmentId))
                TreatmentId = _functions.GetGuid();

            string FileId = "";

            if (value.TreatmentImage.File != null)
                FileId = _functions.SaveFile(value.TreatmentImage.File, user.FirstOrDefault(u => u.Type == "Account").Value);
            else

AppointmentSystem/AppointmentSystem/Views/BaseInfo/DoctorDayOffCreate.cshtml
@model AppointmentSystem.Models.ViewModels.BaseInfoModels.DoctorDayOffCreateVM
@{
    ViewData["Title"] = "醫師手術時間";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card whiteBG mb-4 pattern-F colorset_B">
    <div class="card-header">
        <h3 class="card-title font-weight-bold">@ViewData["Title"]</h3>
    </div>

    <div class="card whiteBG pattern-F colorset_3">
        <div class="card-body">
            <div class="table-responsive" style="overflow-x: unset;">
                <table class="table table-responsive-md table-hover table2 VA-middle">
                    <div class="container">
                        <div class="row justify-content-left">
                            <div class="col-2">
                                <button role="button" class="btn btn-shadow btn-block btn-color11-o" style="background-color:#97dded" onclick="location.href='@Url.Action("DoctorDayOffIndex", "BaseInfo")'">回上頁</button>
                            </div>
                        </div>
                    </div>
                </table>
            </div>
        </div>
    </div>

    <form method="post" asp-action="DoctorDayOffCreate" onsubmit="return verifyData();">
        <div class="card whiteBG mb-4 pattern-F colorset_3">
            <div class="card-body">
                <div class="table-responsive" style="overflow-x: unset;">
                    <table class="table table-responsive-md table-hover table2 VA-middle">
                        <div class="table-responsive">
                            <table class="table table-hover" id="addnew" table-layout: fixed;>
                                <colgroup>
                                    <col width="30%">
                                    <col width="10%">
                                    <col width="30%">
                                    <col width="30%">
                                </colgroup>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td>醫師名稱</td>
                                        <td>@Html.DropDownListFor(m => m.DoctorId, Model.DoctorList, new { @class = "form-control", @required = "", @id = "doctorId" })</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>類別</td>
                                        <td>@Html.DropDownListFor(m => m.Type, Model.TypeList, new { @class = "form-control", @required = "", @id = "type" })</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>開始日期</td>
                                        <td>
                                            <input type="date" id="beginDate" style="width:100%;" asp-for="BeginDate" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>開始時間</td>
                                        <td>@Html.DropDownListFor(m => m.BeginTime, Model.BeginTimeList, new { @class = "form-control", @required = "", @id = "beginTime" })</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>結束日期</td>
                                        <td>
                                            <input type="date" id="endDate" style="width:100%;" asp-for="EndDate" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>結束時間</td>
                                        <td>@Html.DropDownListFor(m => m.EndTime, Model.EndTimeList, new { @class = "form-control", @required = "", @id = "endTime" })</td>
                                        <td></td>
                                    </tr>

                                </tbody>
                            </table>
                            <br>
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                    </div>
                                    <div class="col">
                                        <input type="submit" class="btn btn-shadow btn-color11-3 btn-block" value="儲存">
                                    </div>
                                    <div class="col">
                                    </div>
                                </div>
                            </div>

                        </div>

                    </table>
                </div>
            </div>
        </div>
    </form>

</div>

<script>
    function verifyData() {
        let doctorId = $('#doctorId').val();
        let type = $('#type').val();

        let beginDate = $('#beginDate').val();
        let endDate = $('#endDate').val();

        let beginTime = $('#beginTime').val();
        let endTime = $('#endTime').val();

        beginDate = new Date(beginDate);
        endDate = new Date(endDate);

        beginDate.setHours(0, 0, 0, 0);
        endDate.setHours(0, 0, 0, 0);

        //日期防呆
        if (beginDate < new Date().setHours(0, 0, 0, 0)) {
            alert("開始日期不能是過去的日期。");
            return false;
        }
        if (endDate < new Date().setHours(0, 0, 0, 0)) {
            alert("結束日期不能是過去的日期。");
            return false;
        }
        if (endDate < beginDate) {
            alert("結束日期不能小於開始日期。");
            return false;
        }
        if ($('#beginDate').val() == $('#endDate').val() && endTime <= beginTime) {
            alert("結束時間必須大於開始時間。");
            return false;
        }

        let ajaxFlag = true;

        $.ajax({
            type: 'POST',
            url: '/BaseInfo/CheckDayOffData',
            async: false,
            datatype: "json",
            data: { "doctorId": doctorId, "beginDate": formatDate(beginDate), "endDate": formatDate(endDate), "beginTime": beginTime, "endTime": endTime },
            success: function (data) {
                if (data != "") {
                    alert(data);
                    ajaxFlag = false;
                }
            }
        });

        return ajaxFlag;
    }

    function formatDate(date) {
        let year = date.getFullYear();
        let month = (date.getMonth() + 1).toString().padStart(2, '0');
        let day = date.getDate().toString().padStart(2, '0');
        return `${year}-${month}-${day}`;
    }

</script>

AppointmentSystem/AppointmentSystem/Views/BaseInfo/DoctorDayOffEdit.cshtml
@model AppointmentSystem.Models.ViewModels.SystemModels.FunctionEditVM
@{
    ViewData["Title"] = "功能編輯";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card whiteBG mb-4 pattern-F colorset_B">
    <div class="card-header">
        <h3 class="card-title font-weight-bold">@ViewData["Title"]</h3>
    </div>

    <div class="card whiteBG pattern-F colorset_3">
        <div class="card-body">
            <div class="table-responsive" style="overflow-x: unset;">
                <table class="table table-responsive-md table-hover table2 VA-middle">
                    <div class="container">
                        <div class="row justify-content-left">
                            <div class="col-2">
                                <button role="button" class="btn btn-shadow btn-block btn-color11-o" style="background-color:#97dded" onclick="location.href='@Url.Action("FunctionIndex", "System")'">回上頁</button>
                            </div>
                        </div>
                    </div>
                </table>
            </div>
        </div>
    </div>

    <form method="post" asp-action="FunctionEdit">
        <div class="card whiteBG mb-4 pattern-F colorset_3">
            <div class="card-body">
                <div class="table-responsive" style="overflow-x: unset;">
                    <table class="table table-responsive-md table-hover table2 VA-middle">
                        <div class="table-responsive">
                            <table class="table table-hover" id="addnew" table-layout: fixed;>
                                <colgroup>
                                    <col width="30%">
                                    <col width="10%">
                                    <col width="30%">
                                    <col width="30%">
                                </colgroup>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td>功能名稱</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="FunctionName" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>所屬模組</td>
                                        <td>@Html.DropDownListFor(m=>m.ModuleId, Model.ModuleList , new { @class = "form-control", @required=""})</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>Controller</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="Controller" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>Action</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="Action" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>排序</td>
                                        <td><input type="number" style="width:100%;" asp-for="Sort" required=""></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>備註</td>
                                        <td><input type="text" style="width:100%;" asp-for="Memo"></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>是否啟用</td>
                                        <td>
                                            @Html.DropDownListFor(m=>m.Status, Model.StatusList , new { @class = "form-control"})
                                        </td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>
                            <br>
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                    </div>
                                    <div class="col">
                                        <input type="submit" class="btn btn-shadow btn-color11-3 btn-block" value="儲存">
                                    </div>
                                    <div class="col">
                                    </div>
                                </div>
                            </div>

                        </div>

                    </table>
                </div>
            </div>
        </div>
    </form>

</div>

AppointmentSystem/AppointmentSystem/Views/BaseInfo/DoctorDayOffIndex.cshtml
@model IEnumerable<AppointmentSystem.Models.ViewModels.BaseInfoModels.DoctorDayOffIndexVM>
@{
    ViewData["Title"] = "醫師請假";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card whiteBG mb-4 pattern-F colorset_B">
    <div class="card-header">
        <h3 class="card-title font-weight-bold">@ViewData["Title"]</h3>
    </div>

    <div class="card whiteBG pattern-F colorset_3">
        <div class="card-body">
            <div class="table-responsive" style="overflow-x: unset;">
                <table class="table table-responsive-md table-hover table2 VA-middle">
                    <div class="container">
                        <div class="row justify-content-left">
                            <div class="col-2">
                                <button role="button" class="btn btn-shadow btn-block btn-color11-o" style="background-color:#97dded" onclick="location.href='@Url.Action("DoctorDayOffCreate", "BaseInfo")'">+ 新增請假時間</button>
                            </div>
                        </div>
                    </div>
                </table>
            </div>
        </div>
    </div>

    <div class="card whiteBG mb-4 pattern-F colorset_3">
        <div class="card-body">
            <div class="table-responsive" style="overflow-x: unset;">
                <table class="table table-responsive-md table-hover table2 VA-middle">
                    <div class="table-responsive">
                        <table class="table table-hover" id="addnew" table-layout: fixed;>
                            <colgroup>
                                <col width="15%">
                                <col width="15%">
                                <col width="15%">
                                <col width="15%">
                                <col width="15%">
                                <col width="15%">
                                <col width="10%">
                            </colgroup>
                            <tbody>

                                @if (ViewBag.Count > 0)
                                {
                                    <tr>
                                        <th>醫師名稱</th>
                                        <th>類別</th>
                                        <th>開始日期</th>
                                        <th>開始時間</th>
                                        <th>結束日期</th>
                                        <th>結束時間</th>
                                        <th></th>
                                    </tr>

                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.DoctorName</td>
                                            <td>@item.Type</td>
                                            <td>@item.BeginDate</td>
                                            <td>@item.BeginTime</td>
                                            <td>@item.EndDate</td>
                                            <td>@item.EndTime</td>
                                            @* <td>
                                                <a role="button" class="btn btn-shadow btn-color11-d btn-block" style="background-color:#97dded;" asp-action="DoctorDayOffEdit" asp-route-id="@item.DayOffIndex">
                                                    修改<i class="fas fa-edit"></i>
                                                </a>
                                            </td> *@
                                            <td>
                                                <a href="javascript:void(0)" role="button" class="btn btn-shadow btn-color11-d btn-block" style="background-color:#f97676" onclick="DeleteDayOff('@item.DayOffIndex')">
                                                    刪除<i class="fas fa-trash-alt"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <th>查無資料</th>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>

                </table>
            </div>
        </div>
    </div>


</div>

<script type="text/javascript">
    function DeleteDayOff(Index) {
        if (confirm("確定要刪除這筆請假資料嗎?")) {
            $.ajax({
                type: "POST",
                url: "/BaseInfo/DeleteDoctorDayOff",
                data: { "Index": Index },
                async: false,
                datatype: "json",
                success: function (data) {
                    console.log(data);

                    alert("刪除成功!!");
                    window.location.href = '@Url.Action("DoctorDayOffIndex", "BaseInfo")';
                }
            })
        }
    }
</script>