AppointmentSystem/AppointmentSystem/Components/NavigationViewComponent.cs
using AppointmentSystem.Models.DBModels;
using AppointmentSystem.Models.ViewModels;
using AppointmentSystem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace AppointmentSystem.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        private readonly WebFunctions _functions;

        public NavigationViewComponent(EkasContext context)
        {
            _functions = new WebFunctions(context);
        }

        [Authorize]
        public IViewComponentResult Invoke()
        {
            List<ModuleVM> modules = new List<ModuleVM>();
            var user = HttpContext.User.Claims.ToList();

            if (user.Count != 0)
            {
                if (user.FirstOrDefault(u => u.Type == "IsAdmin").Value == "Y")
                {
                    List<Module> moduleitems = _functions.GetAllModules();

                    foreach (Module item in moduleitems)
                    {
                        List<Function> functionitems = _functions.GetALLFunctionByModule(item.Id);
                        ModuleVM module = new ModuleVM();

                        module.ModuleName = item.ModuleName;
                        module.IsActive = true;

                        foreach (Function function in functionitems)
                        {
                            module.Functions.Add(new FunctionVM()
                            {
                                FunctionName = function.FunctionName,
                                Controller = function.Controller,
                                Action = function.Action,
                                IsActive = true
                            });
                        }

                        modules.Add(module);
                    }
                }
                else
                {
                    List<Module> moduleitems = _functions.GetMoudlesByUserId(user.FirstOrDefault(u => u.Type == "UserId").Value);

                    foreach (Module item in moduleitems)
                    {
                        List<Function> functionitems = _functions.GetFunctionByModule(item.Id, user.FirstOrDefault(u => u.Type == "UserId").Value);
                        ModuleVM module = new ModuleVM();

                        module.ModuleName = item.ModuleName;
                        module.IsActive = true;

                        foreach (Function function in functionitems)
                        {
                            module.Functions.Add(new FunctionVM()
                            {
                                FunctionName = function.FunctionName,
                                Controller = function.Controller,
                                Action = function.Action,
                                IsActive = true
                            });
                        }

                        modules.Add(module);
                    }
                }
            }

            return View(modules);
        }
    }
}

AppointmentSystem/AppointmentSystem/Views/Shared/CustomerLayout.cshtml
<!DOCTYPE html>

<html class="text-center">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>EK美學診所預約系統</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/ekstyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/appointmentsystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />

    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* <script src="~/js/script.js"></script> *@
    <script src="~/js/sweetalert2.min.js"></script>

    <!--load all styles -->
    @*
    <!--自訂CSS-->
    <link rel="stylesheet" href="~/css/rwd.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sweetalert2.css" asp-append-version="true" /> *@
    <style>

    </style>
</head>
<body class="index">
    <header class="header fixed-top" style="background: linear-gradient(to bottom, rgba(255, 255, 255, 0), rgba(255, 255, 255, 0)) ;width:100%; padding-right:0px;">
        <!--style="background: linear-gradient(to bottom, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0));width:100%; padding-right:0px; "-->
        <div class="container d-flex justify-content-between align-items-center" style="padding-left:0px">
            <!--style="padding-left:0px"-->
            <a title="回首頁" asp-controller="Appointment" asp-action="index">
                <img src="~/images/logo_b.png" style="height:3em;width:auto; margin-top:10px; padding-left:0px;" />
                <!--margin-top:10px; padding-left:0px;-->
            </a>

            <a id="logout" asp-area="" asp-controller="Appointment" asp-action="Logout" style="width:15%; display:flex ; justify-content: flex-end; margin-right:10px;">
                <!--style="width:15%; display:flex ; justify-content: flex-end; margin-right:10px;"-->
                <button class="header-toolbar d-flex align-items-center" style="border:none; background-color:#D7F4EE ;padding:5pt; width:30px;height: 30px; border-radius:50% ">
                    <!--style="border:none; font-size:14px  ;padding:5pt; height: 28px;-->
                    <img src="~/images/pill_off_24dp_0E4F43_FILL0_wght400_GRAD0_opsz24.png" />
                </button>
            </a>
        </div>

    </header>

    <div class="content customer-content text-center" style=" max-width:none;padding-bottom:100px; margin:0px;background: linear-gradient(to bottom, #ffffff,  #ffffff) ; padding-left:0px; padding-right:0px;padding-top:0px">
        <!--07061041  style="padding:0px; margin:0px; background-color:transparent;"-->
        @RenderBody()
    </div>



    <footer class="footer  fixed-bottom" style="background: #ffffff;display:none;">
        <div class="container text-center">
        </div>
    </footer>




    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppointmentSystem/AppointmentSystem/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>EK後臺系統</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/appointmentsystem.styles.css" asp-append-version="true" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
    <link rel="stylesheet" href="~/css/fontawesome.min.css" asp-append-version="true" />

    <!--icon font設定-->
    <link rel="stylesheet" href="~/css/all.css" asp-append-version="true" />
    <!--load all styles -->
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <!--自訂CSS-->
    <link rel="stylesheet" href="~/css/rwd.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sweetalert2.css" asp-append-version="true" />

    @*<link rel="icon" href="images/ROC_Water_Resources_Agency_Seal.svg" type="image/ico" />*@

    <!--自訂RWD設定-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body class="index">
    <div class="box">
        @RenderBody()
    </div>

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/js/jquery-3.6.0.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/script.js"></script>
    <script src="~/js/sweetalert2.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppointmentSystem/AppointmentSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="zh-Hant-TW">

<style>
    .header {
        padding: 0px !important;
        height:70px !important;
    }

    .cus-content{
    width:90%;
    margin:auto;
    padding:80px;
    }

    .header-toolbar{
    border-radius:50px !important;
        background-color: #ffffff !important;
        color: #0E4F43 !important;
    }

    .menuBtn{
        border-radius: 50px;
        background-color: #0E4F43;
    }

    .iconBtn{
    width:25px;
    height:25px;
    }
</style>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewData["Title"] - EK預約系統</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/css/ekstyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/appointmentsystem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true">

    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert2.min.js"></script>
</head>

<body>
    <header class="header bg-white fixed-top">
        <div style="width:100%;display: flex; justify-content: center;">
            <div class="d-flex justify-content-between align-items-center layout-header">
                <a title="回首頁" asp-controller="Home" asp-action="index">
                    <img src="~/images/logo_b.png" style="height:3em;width:auto;" />
                </a>

                <button class="header-toolbar d-flex align-items-center">
                    <div class="d-flex flex-column">
                        <span id="header-username">目前使用者: </span>
                        <span id="header-rolename"></span>
                    </div>
                    
                    <div class="menuBtn"><img src="~/images/arrow_drop_down_24dp_D7F4EE_FILL0_wght400_GRAD0_opsz24.png" class="iconBtn" /></div>
                    
                    <div class="dropdown-function bg-white shadow p-3">
                        @await Component.InvokeAsync("Navigation")
                    </div>
                </button>
            </div>
        </div>
    </header>

    <div class="cus-content ">
        @RenderBody()
    </div>

    <footer class="footer bg-light fixed-bottom">
        <div class="container text-right">
            @* <span>鯨明科技有限公司 Copyright © 2024 All Rights Reserved</span> *@
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

<script type="text/javascript">

    $(document).ready(function () {
        init();
        function init() {
            setHeaderUserName();
        }
    });

    document.addEventListener('DOMContentLoaded', function () {
        const toolbar = document.querySelector('.header-toolbar');
        const dropdown = document.querySelector('.dropdown-function');

        toolbar.addEventListener('click', function () {
            dropdown.style.display = dropdown.style.display === 'block' ? 'none' : 'block';
        });

        window.addEventListener('click', function (event) {
            if (!toolbar.contains(event.target)) {
                dropdown.style.display = 'none';
            }
        });
    });

    function setHeaderUserName() {
        $.ajax({
            type: 'POST',
            url: '/Home/setHeaderUserName',
            datatype: "json",
            success: function (data) {
                $('#header-username').html("目前使用者:" + data.username);
                $('#header-rolename').html(data.rolename);
            }
        });
    }
</script>

AppointmentSystem/AppointmentSystem/Views/Shared/__Layout.cshtml
<!DOCTYPE html>

<header id="Header_front">
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: rgb(5, 132, 141);">
        <a class="navbar-brand" title="回首頁" style="color: white;" asp-controller="Home" asp-action="index">EK預約系統</a>
        <ul class="navbar-nav nav-top ml-auto">
            <li class="nav-item">
                <a class="nav-link" title="登出" style="color: white;" asp-area="" asp-controller="Home" asp-action="Logout">登出</a>
            </li>
        </ul>
    </nav>
</header>

<html lang="zh-Hant-TW">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewData["Title"] - EK預約系統</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/appointmentsystem.styles.css" asp-append-version="true" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
    <link rel="stylesheet" href="~/css/fontawesome.min.css" asp-append-version="true" />

    <!--icon font設定-->
    <link rel="stylesheet" href="~/css/all.css" asp-append-version="true" />
    <!--load all styles -->
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <!--自訂CSS-->
    <link rel="stylesheet" href="~/css/rwd.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sweetalert2.css" asp-append-version="true" />

    <!--自訂RWD設定-->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <div id="WRAPPER" class="container-fluid">
        <!-- 內容開始 -->
        <div class="main-left menu_bg_B">
            <div class="menu-control btn-color13">
                <i class="fa fa-chevron-left" aria-hidden="true"></i>
            </div>
            <div class="card" id="accordion" role="tablist" aria-multiselectable="true">
                @await Component.InvokeAsync("Navigation")
            </div>
        </div>
        <div class="main-right">
            <div class="card whiteBG mb-4 pattern-F colorset_B">
                @RenderBody()
            </div>
        </div>

    </div>
    <footer class="inside_footer footer-B" id="Footer_front">
        <div class="container">
            鯨明科技有限公司 Copyright © 2024 All Rights Reserved
        </div>
        <div id="gotop" class="btn-color1" title="回到最上方"><img src="~/images/icon-up.png" alt="回到最上方icon"></div>
    </footer>

    <script src="~/js/jquery-3.6.0.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/script.js"></script>
    <script src="~/js/sweetalert2.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>