AppointmentSystem/AppointmentSystem/Controllers/SystemController.cs
using AppointmentSystem.Models.DBModels;
using AppointmentSystem.Models.ViewModels.SystemModels;
using AppointmentSystem.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using System.Reflection.Metadata;
using static AppointmentSystem.Models.ViewModels.SelectListModels;

namespace AppointmentSystem.Controllers
{
    public class SystemController : Controller
    {
        private readonly SystemService _systemService;
        private readonly WebFunctions _functions;

        public SystemController(EkasContext context)
        {
            _systemService = new SystemService(context);
            _functions = new WebFunctions(context);
        }

        #region -- 系統模組 -- (Module)

        [Authorize]
        public IActionResult ModuleIndex()
        {
            //判斷cookie是員工還是顧客
            var user = HttpContext.User.Claims.ToList();

            if (user.FirstOrDefault(u => u.Type == "LoginType").Value == "EkUser")
            {
                List<ModuleIndexVM> modules = _systemService.GetModuleListForIndex();
                ViewBag.Count = modules.Count;

                return View(modules);
            }
            else
            {
                return RedirectToAction("Login", "Appointment");
            }
        }

        [Authorize]
        public IActionResult ModuleCreate()
        {
            //判斷cookie是員工還是顧客
            var user = HttpContext.User.Claims.ToList();

            if (user.FirstOrDefault(u => u.Type == "LoginType").Value == "EkUser")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Appointment");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult ModuleCreate(ModuleCreateVM value)
        {
            string ModuleId = _functions.GetGuid();

            while (_systemService.CheckModuleId(ModuleId))
                ModuleId = _functions.GetGuid();

            var user = HttpContext.User.Claims.ToList();

            Module item = new Module()
            {
                Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                Modifier = user.FirstOrDefault(u => u.Type == "Account").Value,
                CreateDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                Status = "Y",

                Id = ModuleId,
                ModuleName = value.ModuleName,
                Sort = value.Sort,
                Memo = value.Memo,
            };
            _systemService.CreateModule(item);

            _functions.SaveSystemLog(new Systemlog
            {
                CreateDate = DateTime.Now,
                Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                UserAccount = user.FirstOrDefault(u => u.Type == "Account").Value,
                Description = "Add module id='" + ModuleId + "'."
            });

            return RedirectToAction("ModuleIndex");
        }

        [HttpGet]
        [Authorize]
        public IActionResult ModuleEdit(string id)
        {
            //判斷cookie是員工還是顧客
            var user = HttpContext.User.Claims.ToList();

            if (user.FirstOrDefault(u => u.Type == "LoginType").Value == "EkUser")
            {
                List<SelectListItem> StatusList = _functions.CreateSelectList("StatusList", false);
                ModuleEditVM item = _systemService.GetModuleById(id);

                ModuleEditVM model = new ModuleEditVM() //上面的 Model
                {
                    StatusList = StatusList,
                    Status = item.Status,
                    ModuleName = item.ModuleName,
                    Sort = item.Sort,
                    Memo = item.Memo,
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("Login", "Appointment");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult ModuleEdit(string id, ModuleEditVM value)
        {
            string ModuleId = id;

            var user = HttpContext.User.Claims.ToList();

            Module item = new Module()
            {
                ModifyDate = DateTime.Now,
                Modifier = user.FirstOrDefault(u => u.Type == "Account").Value,

                Id = ModuleId,
                ModuleName = value.ModuleName,
                Memo = value.Memo,
                Status = value.Status!,
                Sort = value.Sort
            };

            _systemService.UpdateModule(id, user.FirstOrDefault(u => u.Type == "Account").Value, item);

            _functions.SaveSystemLog(new Systemlog
            {
                CreateDate = DateTime.Now,
                Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                UserAccount = user.FirstOrDefault(u => u.Type == "Account").Value,
                Description = "Update module id='" + ModuleId + "'."
            });

            return RedirectToAction("ModuleIndex");
        }

        #endregion

        #region -- 系統功能 -- (Function)

        [Authorize]
        public IActionResult FunctionIndex()
        {
            //判斷cookie是員工還是顧客
            var user = HttpContext.User.Claims.ToList();

            if (user.FirstOrDefault(u => u.Type == "LoginType").Value == "EkUser")
            {
                List<FunctionIndexVM> functions = _systemService.GetFunctionListForIndex();
                ViewBag.Count = functions.Count;

                return View(functions);
            }
            else
            {
                return RedirectToAction("Login", "Appointment");
            }
        }

        [Authorize]
        public IActionResult FunctionCreate()
        {
            //判斷cookie是員工還是顧客
            var user = HttpContext.User.Claims.ToList();

            if (user.FirstOrDefault(u => u.Type == "LoginType").Value == "EkUser")
            {
                List<SelectListItem> ModuleList = CreateModuleList();

                FunctionCreateVM model = new FunctionCreateVM() //上面的 Model
                {
                    ModuleList = ModuleList
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("Login", "Appointment");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult FunctionCreate(FunctionCreateVM value)
        {
            string FunctionId = _functions.GetGuid();

            while (_systemService.CheckFunctionId(FunctionId))
                FunctionId = _functions.GetGuid();

            var user = HttpContext.User.Claims.ToList();

            Function item = new Function()
            {
                Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                Modifier = user.FirstOrDefault(u => u.Type == "Account").Value,
                CreateDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                Status = "Y",

                Id = FunctionId,
                FunctionName = value.FunctionName,
                ModuleId = value.ModuleId,
                Controller = value.Controller,
                Action = value.Action,
                Sort = value.Sort,
                Memo = value.Memo,
            };
            _systemService.CreateFunction(item);

            _functions.SaveSystemLog(new Systemlog
            {
                CreateDate = DateTime.Now,
                Creator = user.FirstOrDefault(u => u.Type == "Account").Value,
                UserAccount = user.FirstOrDefault(u => u.Type == "Account").Value,
                Description = "Add function id='" + FunctionId + "'."
            });

            return RedirectToAction("FunctionIndex");
        }

        [HttpGet]
        [Authorize]
        public IActionResult FunctionEdit(string id)
        {
            //判斷cookie是員工還是顧客
            var user = HttpContext.User.Claims.ToList();

            if (user.FirstOrDefault(u => u.Type == "LoginType").Value == "EkUser")
            {
                List<SelectListItem> ModuleList = CreateModuleList();
                List<SelectListItem> StatusList = _functions.CreateSelectList("StatusList", false);
                FunctionEditVM item = _systemService.GetFunctionById(id);

                FunctionEditVM model = new FunctionEditVM() //上面的 Model
                {
                    ModuleList = ModuleList,
                    StatusList = StatusList,
                    Status = item.Status,

                    FunctionName = item.FunctionName,
                    ModuleId = item.ModuleId,
                    Controller = item.Controller,
                    Action = item.Action,
                    Sort = item.Sort,
                    Memo = item.Memo,
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("Login", "Appointment");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult FunctionEdit(string id, FunctionEditVM value)
        {
            string FunctionId = id;

            var user = HttpContext.User.Claims.ToList();

            Function item = new Function()
            {
                Id = FunctionId,
                FunctionName = value.FunctionName,
                ModuleId = value.ModuleId,
                Controller = value.Controller,
                Action = value.Action,
                Sort = value.Sort,
                Memo = value.Memo,
                Status = value.Status!
            };

            _systemService.UpdateFunction(id, user.FirstOrDefault(u => u.Type == "Account").Value, item);

            _functions.SaveSystemLog(new Systemlog
            {
                CreateDate = DateTime.Now,

AppointmentSystem/AppointmentSystem/Views/System/FunctionCreate.cshtml
@model AppointmentSystem.Models.ViewModels.SystemModels.FunctionCreateVM
@{
    ViewData["Title"] = "功能新增";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card whiteBG mb-4 pattern-F colorset_B">
    <div class="card-header">
        <h3 class="card-title font-weight-bold">@ViewData["Title"]</h3>
    </div>

    <div class="card whiteBG pattern-F colorset_3">
        <div class="card-body">
            <div class="table-responsive" style="overflow-x: unset;">
                <table class="table table-responsive-md table-hover table2 VA-middle">
                    <div class="container">
                        <div class="row justify-content-left">
                            <div class="col-2">
                                <button role="button" class="btn btn-shadow btn-block btn-color11-o" style="background-color:#97dded" onclick="location.href='@Url.Action("FunctionIndex", "System")'">回上頁</button>
                            </div>
                        </div>
                    </div>
                </table>
            </div>
        </div>
    </div>

    <form method="post" asp-action="FunctionCreate">
        <div class="card whiteBG mb-4 pattern-F colorset_3">
            <div class="card-body">
                <div class="table-responsive" style="overflow-x: unset;">
                    <table class="table table-responsive-md table-hover table2 VA-middle">
                        <div class="table-responsive">
                            <table class="table table-hover" id="addnew" table-layout: fixed;>
                                <colgroup>
                                    <col width="30%">
                                    <col width="10%">
                                    <col width="30%">
                                    <col width="30%">
                                </colgroup>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td>功能名稱</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="FunctionName" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>所屬模組</td>
                                        <td>@Html.DropDownListFor(m=>m.ModuleId, Model.ModuleList , new { @class = "form-control", @required=""})</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>Controller</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="Controller" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>Action</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="Action" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>排序</td>
                                        <td><input type="number" style="width:100%;" asp-for="Sort" required=""></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>備註</td>
                                        <td><input type="text" style="width:100%;" asp-for="Memo"></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>
                            <br>
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                    </div>
                                    <div class="col">
                                        <input type="submit" class="btn btn-shadow btn-color11-3 btn-block" value="儲存">
                                    </div>
                                    <div class="col">
                                    </div>
                                </div>
                            </div>

                        </div>

                    </table>
                </div>
            </div>
        </div>
    </form>

</div>

AppointmentSystem/AppointmentSystem/Views/System/FunctionEdit.cshtml
@model AppointmentSystem.Models.ViewModels.SystemModels.FunctionEditVM
@{
    ViewData["Title"] = "功能編輯";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card whiteBG mb-4 pattern-F colorset_B">
    <div class="card-header">
        <h3 class="card-title font-weight-bold">@ViewData["Title"]</h3>
    </div>

    <div class="card whiteBG pattern-F colorset_3">
        <div class="card-body">
            <div class="table-responsive" style="overflow-x: unset;">
                <table class="table table-responsive-md table-hover table2 VA-middle">
                    <div class="container">
                        <div class="row justify-content-left">
                            <div class="col-2">
                                <button role="button" class="btn btn-shadow btn-block btn-color11-o" style="background-color:#97dded" onclick="location.href='@Url.Action("FunctionIndex", "System")'">回上頁</button>
                            </div>
                        </div>
                    </div>
                </table>
            </div>
        </div>
    </div>

    <form method="post" asp-action="FunctionEdit">
        <div class="card whiteBG mb-4 pattern-F colorset_3">
            <div class="card-body">
                <div class="table-responsive" style="overflow-x: unset;">
                    <table class="table table-responsive-md table-hover table2 VA-middle">
                        <div class="table-responsive">
                            <table class="table table-hover" id="addnew" table-layout: fixed;>
                                <colgroup>
                                    <col width="30%">
                                    <col width="10%">
                                    <col width="30%">
                                    <col width="30%">
                                </colgroup>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td>功能名稱</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="FunctionName" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>所屬模組</td>
                                        <td>@Html.DropDownListFor(m=>m.ModuleId, Model.ModuleList , new { @class = "form-control", @required=""})</td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>Controller</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="Controller" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>Action</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="Action" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>排序</td>
                                        <td><input type="number" style="width:100%;" asp-for="Sort" required=""></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>備註</td>
                                        <td><input type="text" style="width:100%;" asp-for="Memo"></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>是否啟用</td>
                                        <td>
                                            @Html.DropDownListFor(m=>m.Status, Model.StatusList , new { @class = "form-control"})
                                        </td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>
                            <br>
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                    </div>
                                    <div class="col">
                                        <input type="submit" class="btn btn-shadow btn-color11-3 btn-block" value="儲存">
                                    </div>
                                    <div class="col">
                                    </div>
                                </div>
                            </div>

                        </div>

                    </table>
                </div>
            </div>
        </div>
    </form>

</div>

AppointmentSystem/AppointmentSystem/Views/System/FunctionIndex.cshtml
@model IEnumerable<AppointmentSystem.Models.ViewModels.SystemModels.FunctionIndexVM>
@{
    ViewData["Title"] = "功能管理";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card whiteBG mb-4 pattern-F colorset_B">
    <div class="card-header">
        <h3 class="card-title font-weight-bold">@ViewData["Title"]</h3>
    </div>

    <div class="card whiteBG pattern-F colorset_3">
        <div class="card-body">
            <div class="table-responsive" style="overflow-x: unset;">
                <table class="table table-responsive-md table-hover table2 VA-middle">
                    <div class="container">
                        <div class="row justify-content-left">
                            <div class="col-2">
                                <button role="button" class="btn btn-shadow btn-block btn-color11-o" style="background-color:#97dded" onclick="location.href='@Url.Action("FunctionCreate", "System")'">+ 新增模組</button>
                            </div>
                        </div>
                    </div>
                </table>
            </div>
        </div>
    </div>

    <div class="card whiteBG mb-4 pattern-F colorset_3">
        <div class="card-body">
            <div class="table-responsive" style="overflow-x: unset;">
                <table class="table table-responsive-md table-hover table2 VA-middle">
                    <div class="table-responsive">
                        <table class="table table-hover" id="addnew" table-layout: fixed;>
                            <colgroup>
                                <col width="20%">
                                <col width="15%">
                                <col width="10%">
                                <col width="30%">
                                <col width="10%">
                                <col width="15%">
                            </colgroup>
                            <tbody>

                                @if (ViewBag.Count > 0)
                                {
                                    <tr>
                                        <th>功能名稱</th>
                                        <th>所屬模組</th>
                                        <th>排序</th>
                                        <th>備註</th>
                                        <th>是否啟用</th>
                                        <th></th>
                                    </tr>

                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.FunctionName</td>
                                            <td>@item.ModuleName</td>
                                            <td>@item.Sort</td>
                                            <td>@item.Memo</td>
                                            <td>@item.Status</td>
                                            <td>
                                                <a role="button" class="btn btn-shadow btn-color11-d btn-block" style="background-color:#97dded;" asp-action="FunctionEdit" asp-route-id="@item.FunctionId">
                                                    修改<i class="fas fa-edit"></i>
                                                </a>
                                            </td>
                                            <!--
                                            <td>
                                                <a href="javascript:void(0)" role="button" class="btn btn-shadow btn-color11-d btn-block" style="background-color:#f97676" onclick="DeleteQuestion('@item.FunctionId')">
                                                    刪除<i class="fas fa-trash-alt"></i>
                                                </a>
                                            </td>
                                            -->
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <th>查無資料</th>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>

                </table>
            </div>
        </div>
    </div>


</div>

AppointmentSystem/AppointmentSystem/Views/System/LabelEdit.cshtml
@model AppointmentSystem.Models.ViewModels.SystemModels.LabelEditVM
@{
    ViewData["Title"] = "標籤修改";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card whiteBG mb-4 pattern-F colorset_B">
    <div class="card-header">
        <h3 class="card-title font-weight-bold">@ViewData["Title"]</h3>
    </div>

    <div class="card whiteBG pattern-F colorset_3">
        <div class="card-body">
            <div class="table-responsive" style="overflow-x: unset;">
                <table class="table table-responsive-md table-hover table2 VA-middle">
                    <div class="container">
                        <div class="row justify-content-left">
                            <div class="col-2">
                                <button role="button" class="btn btn-shadow btn-block btn-color11-o" style="background-color:#97dded" onclick="location.href='@Url.Action("LabelIndex", "System")'">回上頁</button>
                            </div>
                        </div>
                    </div>
                </table>
            </div>
        </div>
    </div>

    <form method="post" asp-action="LabelEdit">
        <div class="card whiteBG mb-4 pattern-F colorset_3">
            <div class="card-body">
                <div class="table-responsive" style="overflow-x: unset;">
                    <table class="table table-responsive-md table-hover table2 VA-middle">
                        <div class="table-responsive">
                            <table class="table table-hover" id="addnew" table-layout: fixed;>
                                <colgroup>
                                    <col width="30%">
                                    <col width="10%">
                                    <col width="30%">
                                    <col width="30%">
                                </colgroup>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td>標籤名稱</td>
                                        <td>
                                            <input type="text" style="width:100%;" asp-for="LabelName" required="">
                                        </td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>排序</td>
                                        <td><input type="number" style="width:100%;" asp-for="Sort" required=""></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td>是否啟用</td>
                                        <td>
                                            @Html.DropDownListFor(m=>m.Status, Model.StatusList , new { @class = "form-control"})
                                        </td>
                                        <td></td>
                                    </tr>
                                    
                                </tbody>
                            </table>
                            <br>
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                    </div>
                                    <div class="col">
                                        <input type="submit" class="btn btn-shadow btn-color11-3 btn-block" value="儲存">
                                    </div>
                                    <div class="col">
                                    </div>
                                </div>
                            </div>

                        </div>

                    </table>
                </div>
            </div>
        </div>
    </form>

</div>